### PR TITLE
Add minimal compatibility with vibes

### PR DESCRIPTION
**Pull request by sirmarcel**
[`vibes`](https://gitlab.com/vibes-developers/vibes/) is a toolkit for vibrational simulations with `ase`. This patch makes a very minimal change to allow `FHI-vibes` workflows to use the NequIP calculator. 

This does not address more subtle features, but it's good enough for experimental use. I'm not sure if this should be merged yet -- I just wanted to start the conversation. We'll be using this internally to explore NequIP in any case. :)

## Description

The only change is that it adds a function that takes a path to a deployed model file as input and returns the calculator. This is needed because the `vibes` infrastructure uses an input-file approach where you can define: a) the module from which to import a calculator, b) the name of the class/function that generates it, and c) a bunch of `kwargs` to be passed to the function or constructor in (b). Class methods can't be used in this way, so we can't make use of the `from_deployed_model` method. We may change this in the future, of course, but this is an easier fix for now.

The requisite input block for `vibes` looks like this:
```
[calculator]
name:                          nequip_calculator
module:                        nequip.ase.nequip_calculator

[calculator.parameters]
model:                         path/to/model.pth

```

## Motivation and Context
This enables `vibes` to use the NequIP calculator. Out of the box, this allows us to compute phonon band structures, run MD, do relaxations, etc. More complicated issues, such as stress, are not yet addressed.

## How Has This Been Tested?
I ran a short MD with a trained model and computed the VDOS compared to a baseline -- it looks fine. In fact, NequIP does very well! I think this change is small enough to not require extensive testing.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds or improves functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:
- [x] My code follows the code style of this project and has been formatted using `black`.
- [x] All new and existing tests passed.
- [ ] I have added tests that cover my changes (if relevant).
- [ ] The option documentation (`docs/options`) has been updated with new or changed options.
- [ ] I have updated `CHANGELOG.md`.
- [ ] I have updated the documentation (if relevant).

I consider this change to be too small to require inclusion in the changelog.

### CODE REVIEW

**Review by simonbatzner — APPROVED** [review]

**Comment by simonbatzner** [comment]
Hi @sirmarcel, thanks for the PR, `vibes` looks like a great tool. We changed the PR to be merged onto `develop`, which we periodically merge onto `main` and have also updated `CHANGELOG.md`. 

Let us know if you have other, more extensive changes you'd like to make. Unless you object, I will merge this for now so that you can go ahead and start using it.

**Comment by sirmarcel** [comment]
Thanks! I think you can go ahead for now, I'll open a discussion if/when we need to make more extensive changes.

**Comment by Linux-cpp-lisp** [comment]
@sirmarcel just letting you know that I've [released v0.5.1](https://github.com/mir-group/nequip/releases/tag/v0.5.1) to `main`, which includes this PR, so your code should now be usable with the "stable" release.

**Comment by sirmarcel** [comment]
Thank you, that's good to know!

**Pull request merged**
