### PR TITLE
Geometric 1.7.1 compatibility

### LINKED ISSUE #45: 🐛 [BUG] Compatibility with torch1.9, geometric1.7, e3nn 0.3.2
**Describe the bug**
torch.jit.script cannot take dict for typing.Dict .

**To Reproduce**
Unit test tests/data/test_AtomicData.py::test_non_periodic_edge  will fail with pytorch1.9 and torch_geometric 1.7

**Environment (please complete the following information):**
 - OS: Fedora
 - python version 3.8.8
 - python environment:
   - nequip version 0.3.2
   - e3nn version 0.3.2
   - pytorch version 1.9.0+cu102

Pytest error message:

`========================================== FAILURES ==========================================
______________________________ test_non_periodic_edge[float32] _______________________________

CH3CHO = (Atoms(symbols='OCHCH3', pbc=False), AtomicData(edge_index=[2, 18], pos=[7, 3], num_nodes=7, atomic_numbers=[7], cell=[3, 3], edge_cell_shift=[18, 3], pbc=[3]))

    def test_non_periodic_edge(CH3CHO):
        atoms, data = CH3CHO
        # check edges
        for edge in range(data.num_edges):
            real_displacement = (
                atoms.positions[data.edge_index[1, edge]]
                - atoms.positions[data.edge_index[0, edge]]
            )
>           assert torch.allclose(
                data.get_edge_vectors()[edge],
                torch.as_tensor(real_displacement, dtype=torch.get_default_dtype()),
            )

tests/data/test_AtomicData.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

data = AtomicData(edge_index=[2, 18], pos=[7, 3], num_nodes=7, atomic_numbers=[7], cell=[3, 3], edge_cell_shift=[18, 3], pbc=[3])

    def get_edge_vectors(data: Data) -> torch.Tensor:
>       data = AtomicDataDict.with_edge_vectors(AtomicData.to_AtomicDataDict(data))
E       RuntimeError: with_edge_vectors() Expected a value of type 'Dict[str, Tensor]' for argument 'data' but instead found type 'dict'.
E       Position: 0
E       Value: {'atomic_numbers': tensor([8, 6, 1, 6, 1, 1, 1]), 'num_nodes': 7, 'pos': tensor([[ 1.2181,  0.3612,  0.0000],
E               [ 0.0000,  0.4641,  0.0000],
E               [-0.4772,  1.4653,  0.0000],
E               [-0.9481, -0.7001,  0.0000],
E               [-0.3859, -1.6342,  0.0000],
E               [-1.5963, -0.6525,  0.8809],
E               [-1.5963, -0.6525, -0.8809]]), 'edge_index': tensor([[0, 1, 1, 1, 2, 3, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6],
E               [1, 3, 0, 2, 1, 5, 6, 4, 1, 3, 5, 6, 6, 4, 3, 5, 3, 4]]), 'edge_cell_shift': tensor([[0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.]]), 'pbc': tensor([False, False, False]), 'cell': tensor([[0., 0., 0.],
E               [0., 0., 0.],
E               [0., 0., 0.]])}
E       Declaration: with_edge_vectors(Dict(str, Tensor) data, bool with_lengths=True) -> (Dict(str, Tensor))
E       Cast error details: Unable to cast Python instance to C++ type (compile in debug mode for details)

nequip/data/AtomicData.py:253: RuntimeError
`

### PR DESCRIPTION
**Pull request by nw13slx**
## Description
torch geometric 1.7 changes some variable names for the Data class. And `num_graph` somehow enter the data.keys, which contaminates some conversion procedures. 
e3nn0.3.2 also update the fully connected layer class attributes, which will break the initializers in configs/minimal.yaml.

## Motivation and Context

close #45 

## How Has This Been Tested?
all current tests passed. (without the pull , it will not work with the latest e3nn and torch_geometric)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds or improves functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation improvement (updates to user guides, docstrings, or developer docs)

## Checklist:

- [x] My code follows the code style of this project and has been formatted using `black`.
- [x] I have updated the documentation (if relevant).
- [ ] I have added tests that cover my changes (if relevant).
- [x] All new and existing tests passed.
- [ ] `example.yaml` (and other relevant `configs/`) have been updated with new or changed options.
- [x] I have updated `CHANGELOG.md`.

### CODE REVIEW

**Comment by nw13slx** [comment]
with pytorch1.9, the opt_einsum_fx will raise warning while running `nequip-train configs/minimal.yaml` :

```
opt_einsum_fx/opt_einsum_fx/_opt_ein.py:119: RuntimeWarning: einsum einsum lacked shape information; not optimizing. Did you forget to run ShapeProp on this graph?
```

**Comment by Linux-cpp-lisp** [comment]
@nw13slx I think I resolved the e3nn stuff (which was actually for 0.3.3, I think) —  can you review?

I will take a look in a seperate place at the torch 1.9 stuff

**Comment by Linux-cpp-lisp** [comment]
opt_einsum problems are resolved there for torch 1.9 in 0.1.2

**Comment by nw13slx** [comment]
> @nw13slx I think I resolved the e3nn stuff (which was actually for 0.3.3, I think) — can you review?
> 
> I will take a look in a seperate place at the torch 1.9 stuff

I think this looks good! :+1:

**Review by Linux-cpp-lisp — APPROVED** [review]

**Pull request merged**
